# -*- coding: utf-8 -*-
"""task 2.4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJ9qj2XKDol6oSw6Em2TnGI7jikUJvSp

Задача 2.4

**A**
"""

def remove_exclamation_marks(s):
    result = s.replace('!', '')
    return result

print(remove_exclamation_marks("Hi! Hello!")) 
print(remove_exclamation_marks("")) 
print(remove_exclamation_marks("Oh, no!!!"))

"""Задача 2.4

**B**
"""

def remove_last_em(s):
    if s.endswith('!'):
        s = s[:-1]
    return s
print(remove_last_em("Hi!"))
print(remove_last_em("Hi!!!"))
print(remove_last_em("!Hi"))

"""Задача 2.4

**C**
"""

def remove_word_with_one_em(s):
    words = s.split(' ')
    result = []
    for word in words:
        if word.count('!') == 1:
            continue
        result.append(word)
    result_s = ' '.join(result)
    return result_s
print(remove_word_with_one_em("Hi!"))
print(remove_word_with_one_em("Hi! Hi!"))
print(remove_word_with_one_em("Hi! Hi! Hi!"))
print(remove_word_with_one_em("Hi Hi! Hi!"))
print(remove_word_with_one_em("Hi! !Hi Hi!"))
print(remove_word_with_one_em("Hi! Hi!! Hi!") )
print(remove_word_with_one_em("Hi! !Hi! Hi!"))