# -*- coding: utf-8 -*-
"""task 2.3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJ9qj2XKDol6oSw6Em2TnGI7jikUJvSp

Задача 2.3
"""

number=int(input('Введите число: '))
def switch_it_up(number):
    words_dict = {
        0: 'Zero',
        1: 'One',
        2: 'Two',
        3: 'Three',
        4: 'Four',
        5: 'Five',
        6: 'Six',
        7: 'Seven',
        8: 'Eight',
        9: 'Nine'
    }
    return words_dict.get(number)
print(switch_it_up(number))