# -*- coding: utf-8 -*-
"""task 2.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJ9qj2XKDol6oSw6Em2TnGI7jikUJvSp

Задача 2.1
"""

privet=[4,6,2,1,9,63,-134,566]
#privet=[-52, 56, 30, 29, -54, 0, -110]
#privet=[42, 54, 65, 87, 0]
#privet=[5] 
def minimum (privet):
    mini_element = privet[0]
    for i in privet:
        if mini_element>i:
            mini_element=i
    return mini_element
def maximum (privet):
    maxi_element = privet[0]
    for i in privet:
        if maxi_element<i:
            maxi_element=i
    return maxi_element
print('max=', maximum(privet), end=',') 
print('min=', minimum(privet))