# -*- coding: utf-8 -*-
"""task 1.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJ9qj2XKDol6oSw6Em2TnGI7jikUJvSp

Исправляю решение задачи 1.1
"""

favorite_songs = 'Waste a Moment, Staying\' Alive, A Sorta Fairytale, Start Me Up, New Salvation'
my_favorite_songs_str = favorite_songs.split(',')
print (my_favorite_songs_str[0],  my_favorite_songs_str[-1],  my_favorite_songs_str[1],  my_favorite_songs_str[-2], sep='\n')